# Generated by Django 3.2.12 on 2022-02-18 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='contato',
            options={'verbose_name': 'contato', 'verbose_name_plural': 'contatos'},
        ),
        migrations.RemoveField(
            model_name='contato',
            name='data_criacao',
        ),
        migrations.AlterField(
            model_name='contato',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='contatos.categoria'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
